# Generated by Django 4.1.7 on 2023-02-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_randomnumber_delete_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
